kind: Service
apiVersion: v1
metadata: 
 name: my-loadbalancer-service
spec:
 type: LoadBalancer
 selector:
  app: webserver
 ports:
  - name: http
    port: 80  #Service Port
    targetPort: 80 #Container port
