kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-app
  labels: 
    app: backend-app
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
    app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
        tier: backend
    spec: 
      containers:
        - name: backend-app
          image: stacksimplify/kube-helloworld:1.0.0
          ports:
          containerPort: 8080
