kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-nginx-web
spec:
  replicas : 3
  selector:
    matchLabels:
      app: frontend-nginx-web
  template:
    metadata:
      labels:
        app: frontend-nginx-web
    spec:
      containers:
        - name: frontend-nginx-web
          image: stacksimplify/kube-frontend-nginx:1.0.0
          ports:
            - containerPort: 80
