apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: frontend-nginx-web
  ports:
  - port: 80   # Service port
    targetPort: 80  #Container Port
