apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium-retain-sc
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain  #volume will be retain till K8s cluster not deleted
volumeBindingMode: WaitForFirstConsumer # it will create when first pod created
allowVolumeExpansion: true
parameters:
  storageAccountType: Premium_LRS
  kind: managed
