apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermgmt-webapp
  labels: 
    app: usermgmt-webapp
spec:
  replicas: 1
  selector: 
  template:
    metadata:
      lavels:
        app: usermgmt-webapp
    spec:
      initContainers:
        - name : init-db
          image: busybox:1.31
          command: ['sh','-c', 'echo -e "checking for availability of mysql server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e ">> mysqlserver has started";']
      containers:
        - name : usermgmt-webapp
          image: stacksimplify/kube-usermgmt-webapp:1.0.0-MySQLDB
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOSTNAME
              value: "mysql"
            - name: DP_PORT
              value: "3306"
            - name: DB_NAME
              value: "webappdb"
            - name: DB_USERNAEM
              value: "root"
            - name: DB_PASSWORD
              value: "dbpassword11"
