apiVersion: v1
kind: apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ExternalName
  externalName: mysqlserver01june23.mysql.database.azure.com

  ## command to connect mysql db from AKS
  ##kubectl run -it --rm --image=mysql:5.7.22 --restart=Never mysql-client -- mysql -h <>.mysql.database.azure.com -u <> -p<> 
